### ISSUE TITLE
API communication

### ISSUE THREAD

**Issue by samichoulo911** [TurboAudio/turbo_audio#10]
Here are the requirements for the communication between the clients and the server:
- Real-time updates on selected resources (we don't want clients to receive data about resources they are not interested in)
- Avoid clients implementing real-time update by polling from the client. We want the server to push updates to the clients.

**Proposed solution for resource selection**
To avoid sending information the client will not be using, we should only send information to the client if he specifically asked for said information. There should be layers of subscriptions.
Example: If a client asks to subscribe to LedStrip events, it would receive led strip creation/deletion/update events regardless of their ids. This could be useful for a dashboard displaying only the led strip information. This client would not receive information about the modifications done to the effects of this led strip because it is not subscribed to Effect events.

On the other hand, a client could subscribe to a specific resource hereby receiving updates about this resource in particular.
Example: If a client subscribes to the effect with id 34, it will only be notified of modifications done to this effect.

Ideally, this logic would be done server-side to avoid unnecessary networking load.

**Proposed protocol**
For real-time updates, WebSocket connection is probably the best approach as it uses TCP that ensures the integrity and ordering of the messages.
For create/delete/update/get requests on the other hand we have the following options:
- Add a REST api to the server allowing clients to make create/delete/update/get requests
- Use the existing WebSocket connection to make requests (reimplement the request/response mechanism)
- Add WS wrapper that adds those features? (there may exist a protocol that adds features to the ws connection)

Each of the options have their own pros/cons:
- **REST api + websocket**: Since the REST requests don't use the same TCP connection as the websocket, some updates might be received by the client before the REST response is received causing the resource to be out of sync with the server. This could be resolved by adding timestamps to the request responses and the websocket messages but some extra logic would also be required to apply the missed updates on the resources. Although this adds some complexity to the clients websocket management code, the client can easily `await` on server requests. Also, every application wanting real-time notifications of the server would have to implement the logic ensuring that the missing updates are applied to the REST response.
- **Using WebSocket to make requests**: This solution would remove the complexity of keeping two protocols "in sync", but would be adding a custom protocol to the connection. Since the WebSocket connection is event based, it is not possible to make REST requests with the default WebSocket connection. A client wanting to get the current state of a resource, would have to send a message through the ws-connection and wait for the server to reply. Since the client can't be sure that the next message received will be the response to his request, a request-id would probably be needed in order to determine which message corresponds the request response. Clients will have to implement the wrapping logic if they want to `await` on a request they made to the server.

This is just my initial thought. More discussion is needed.

**Comment by samichoulo911** [comment]
After running a test using REST and WS, I was able to recreate the issue I thought could happen.
Server-side, we simulate another user sending an update before the return value can be sent.
![image](https://user-images.githubusercontent.com/43357319/200197323-31c5bda5-88db-47c7-ba01-cfd7883878b3.png)

Client side, the REST client and the WS client try to grab the same mutex (indexed by resource id) and we count the number of time each one failed to grab it.
![image](https://user-images.githubusercontent.com/43357319/200197508-91fb1574-4d6d-471b-b23c-60d6cbf168fa.png)

If we run the server and the client on the same machine, no problem is detected.
If we run the client on another machine on the local network, ~1.5% of the locks are taken by the WS client.

**Comment by SGauvin** [comment]
This will be done via a general plugin (plugin that can add functionality to turbo audio)
