### ISSUE TITLE
Audio processing

### ISSUE THREAD

**Issue by SGauvin** [TurboAudio/turbo_audio#18]
Useful links:
https://github.com/RustAudio
https://github.com/MeadowlarkDAW/audio-filters
https://github.com/RustAudio/dasp
https://github.com/RustAudio/rimd (midi in rust @samichoulo911)

**Comment by SGauvin** [comment]
https://github.com/katyo/aubio-rs

**Comment by samichoulo911** [comment]
Dasp ca a lair turbo gyu
